### ISSUE TITLE
Does not install into VS2022

### ISSUE THREAD

**Issue by m1bcodes** [gharveymn/MEXFunctionTemplates-VS#3]
When closing VS after installing the extension, the following error message is displayed:

> 02.06.2022 22:50:20 - Microsoft VSIX Installer
> 02.06.2022 22:50:20 - -------------------------------------------
> 02.06.2022 22:50:20 - vsixinstaller.exe version:
> 02.06.2022 22:50:20 - 17.2.2174
> 02.06.2022 22:50:20 - -------------------------------------------
> 02.06.2022 22:50:20 - Command line parameters:
> 02.06.2022 22:50:20 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:17.1.32421.90,/appidname:Microsoft Visual Studio Community 2022,/culture:en-US,/noep,C:\Users\mibu\AppData\Local\Temp\VSIXsjrvcm1t.vsix
> 02.06.2022 22:50:20 - -------------------------------------------
> 02.06.2022 22:50:20 - Microsoft VSIX Installer
> 02.06.2022 22:50:20 - -------------------------------------------
> 02.06.2022 22:50:20 - Initializing Install...
> 02.06.2022 22:50:21 - Extension Details...
> 02.06.2022 22:50:21 - 	Identifier         : MEXFunctionTemplates.b07898e3-52e5-4a61-9790-06df0ff75826
> 02.06.2022 22:50:21 - 	Name               : MEX Function Templates
> 02.06.2022 22:50:21 - 	Author             : Gene Harvey
> 02.06.2022 22:50:21 - 	Version            : 1.0.2
> 02.06.2022 22:50:21 - 	Description        : Provides templates for creating MEX functions in C and C++.
> 02.06.2022 22:50:21 - 	Locale             : en-US
> 02.06.2022 22:50:21 - 	MoreInfoURL        : https://github.com/gharveymn/MEXFunctionTemplates-VS
> 02.06.2022 22:50:21 - 	InstalledByMSI     : False
> 02.06.2022 22:50:21 - 	SupportedFrameworkVersionRange : [4.5,)
> 02.06.2022 22:50:21 - 
> 02.06.2022 22:50:21 - 	SignatureState     : Unsigned
> 02.06.2022 22:50:21 - 	Supported Products : 
> 02.06.2022 22:50:21 - 		Microsoft.VisualStudio.Community
> 02.06.2022 22:50:21 - 			Version : [12.0,17.0)
> 02.06.2022 22:50:21 - 			ProductArchitecture : x86
> 02.06.2022 22:50:21 - 		Microsoft.VisualStudio.Pro
> 02.06.2022 22:50:21 - 			Version : [12.0,17.0)
> 02.06.2022 22:50:21 - 			ProductArchitecture : x86
> 02.06.2022 22:50:21 - 		Microsoft.VisualStudio.Enterprise
> 02.06.2022 22:50:21 - 			Version : [12.0,17.0)
> 02.06.2022 22:50:21 - 			ProductArchitecture : x86
> 02.06.2022 22:50:21 - 
> 02.06.2022 22:50:21 - 	References         : 
> 02.06.2022 22:50:21 - 	Prerequisites      : 
> 02.06.2022 22:50:21 - 		-------------------------------------------------------
> 02.06.2022 22:50:21 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
> 02.06.2022 22:50:21 - 		Name         : Visual Studio core editor
> 02.06.2022 22:50:21 - 		Version      : [12.0,17.0)
> 02.06.2022 22:50:21 - 
> 02.06.2022 22:50:21 - Signature Details...
> 02.06.2022 22:50:21 - 	Extension is not signed.
> 02.06.2022 22:50:21 - 
> 02.06.2022 22:50:21 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
>    bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    bei VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
>    bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    bei VSIXInstaller.App.Initialize()
>    bei System.Threading.Tasks.Task`1.InnerInvoke()
>    bei System.Threading.Tasks.Task.Execute()
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
> 
> 

Visual Studio version is 17.1.6 Community

**Comment by gharveymn** [comment]
That's weird. It seems to be trying to install 1.0.2, but the store shows that it's on 1.0.3, which added support for VS2022. I'm also able to reproduce it on my end. Thanks for the report, I'll look into it.

**Comment by gharveymn** [comment]
It should be working again (just reuploaded the extension). Affirm it's working for you?

**Comment by m1bcodes** [comment]
Yes confirmed: it is working again.  Thanks a lot.
